"""
SFT Training Script — Fine-tune Qwen3-4B-Instruct on inventory management trajectories.

Uses Unsloth for efficient LoRA + TRL SFTTrainer with chat template auto-applied.

Usage:
    python sft_train.py

Reads: sft_data.jsonl (generated by generate_sft_data.py)
Output: ./sft_model/ (LoRA adapter + tokenizer)
        ./sft_model_merged/ (merged 16-bit weights for GRPO continuation)

Optional env vars:
    SFT_DATA_FILE    — path to training data (default: sft_data.jsonl)
    MIN_REWARD       — only train on examples with reward >= this (default: -999, i.e. all)
    OUTPUT_DIR       — where to save model (default: ./sft_model)
    NUM_EPOCHS       — training epochs (default: 3)
    BATCH_SIZE       — per-device batch size (default: 2)
    GRAD_ACCUM       — gradient accumulation steps (default: 4)
    MAX_SEQ_LENGTH   — max sequence length (default: 4096)
    LEARNING_RATE    — learning rate (default: 1e-4)
"""

import os
import json
import time
import logging

from dotenv import load_dotenv
load_dotenv()

from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig
from datasets import Dataset

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("sft_train")

# --- Config ---
SFT_DATA_FILE = os.getenv("SFT_DATA_FILE", "sft_data.jsonl")
MIN_REWARD = float(os.getenv("MIN_REWARD", "-10"))
OUTPUT_DIR = os.getenv("OUTPUT_DIR", "./sft_model")
NUM_EPOCHS = int(os.getenv("NUM_EPOCHS", "3"))
BATCH_SIZE = int(os.getenv("BATCH_SIZE", "2"))
GRAD_ACCUM = int(os.getenv("GRAD_ACCUM", "4"))
MAX_SEQ_LENGTH = int(os.getenv("MAX_SEQ_LENGTH", "4096"))
LEARNING_RATE = float(os.getenv("LEARNING_RATE", "1e-4"))

MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"


def load_data():
    """Load JSONL and filter by reward threshold. Return HF Dataset with messages format."""
    examples = []
    total_loaded = 0
    total_filtered = 0
    reward_values = []
    with open(SFT_DATA_FILE) as f:
        for line in f:
            ex = json.loads(line.strip())
            total_loaded += 1
            reward_values.append(ex["reward"])
            if ex["reward"] >= MIN_REWARD:
                examples.append({
                    "messages": [
                        {"role": "system", "content": ex["system"]},
                        {"role": "user", "content": ex["user"]},
                        {"role": "assistant", "content": ex["assistant"]},
                    ]
                })
            else:
                total_filtered += 1

    avg_reward = sum(reward_values) / len(reward_values) if reward_values else 0
    log.info(f"Loaded {total_loaded} total, kept {len(examples)} (filtered {total_filtered})")
    log.info(f"Reward stats: avg={avg_reward:.3f}, min={min(reward_values):.3f}, max={max(reward_values):.3f}")
    return Dataset.from_list(examples)


def _smooth(values, window):
    """Rolling average smoothing."""
    smoothed = []
    for i in range(len(values)):
        start = max(0, i - window)
        smoothed.append(sum(values[start:i+1]) / (i - start + 1))
    return smoothed


def plot_training_curves(trainer, output_dir, dataset):
    """Plot and save comprehensive SFT training curves."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        history = trainer.state.log_history
        steps = [h["step"] for h in history if "loss" in h]
        losses = [h["loss"] for h in history if "loss" in h]
        lr_steps = [h["step"] for h in history if "learning_rate" in h]
        lrs = [h["learning_rate"] for h in history if "learning_rate" in h]
        eval_steps = [h["step"] for h in history if "eval_loss" in h]
        eval_losses = [h["eval_loss"] for h in history if "eval_loss" in h]

        if not steps:
            log.warning("No loss data found in training history")
            return

        os.makedirs(output_dir, exist_ok=True)
        window = max(5, len(losses) // 20) if len(losses) > 10 else 1

        # === Figure 1: Main training dashboard (2x2) ===
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        fig.suptitle("SFT Training — QuarterMaster", fontsize=16, fontweight="bold")

        # Top-left: Loss curve (raw + smoothed)
        ax = axes[0, 0]
        ax.plot(steps, losses, color="#3b82f6", linewidth=1, alpha=0.4, label="Raw loss")
        if len(losses) > 10:
            ax.plot(steps, _smooth(losses, window), color="#ef4444", linewidth=2.5,
                    label=f"Smoothed (w={window})")
        if eval_steps:
            ax.plot(eval_steps, eval_losses, color="#22c55e", linewidth=2, marker="o",
                    markersize=5, label="Eval loss")
        ax.set_xlabel("Step")
        ax.set_ylabel("Loss")
        ax.set_title("Training & Eval Loss")
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Top-right: Learning rate schedule
        ax = axes[0, 1]
        if lr_steps:
            ax.plot(lr_steps, lrs, color="#a855f7", linewidth=2)
            ax.set_xlabel("Step")
            ax.set_ylabel("Learning Rate")
            ax.set_title("Learning Rate Schedule")
            ax.ticklabel_format(style="scientific", axis="y", scilimits=(0, 0))
        else:
            ax.text(0.5, 0.5, "No LR data logged", ha="center", va="center",
                    transform=ax.transAxes, color="#888")
            ax.set_title("Learning Rate Schedule")
        ax.grid(True, alpha=0.3)

        # Bottom-left: Loss distribution histogram
        ax = axes[1, 0]
        ax.hist(losses, bins=40, color="#06b6d4", alpha=0.7, edgecolor="#000")
        ax.axvline(x=sum(losses)/len(losses), color="#ef4444", linestyle="--",
                   linewidth=2, label=f"Mean={sum(losses)/len(losses):.4f}")
        ax.set_xlabel("Loss")
        ax.set_ylabel("Count")
        ax.set_title("Loss Distribution")
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Bottom-right: Loss by epoch (if multiple epochs)
        ax = axes[1, 1]
        epoch_data = [h for h in history if "epoch" in h and "loss" in h]
        if epoch_data:
            epochs = [h["epoch"] for h in epoch_data]
            epoch_losses = [h["loss"] for h in epoch_data]
            # Group by integer epoch
            epoch_groups = {}
            for ep, lo in zip(epochs, epoch_losses):
                ep_int = int(ep)
                epoch_groups.setdefault(ep_int, []).append(lo)
            ep_labels = sorted(epoch_groups.keys())
            ep_means = [sum(epoch_groups[e])/len(epoch_groups[e]) for e in ep_labels]
            ax.bar([f"Epoch {e+1}" for e in ep_labels], ep_means,
                   color=["#3b82f6", "#22c55e", "#f59e0b", "#ef4444", "#a855f7"][:len(ep_labels)],
                   width=0.5)
            ax.set_ylabel("Mean Loss")
            ax.set_title("Mean Loss per Epoch")
        else:
            ax.text(0.5, 0.5, "Single epoch", ha="center", va="center",
                    transform=ax.transAxes, color="#888")
            ax.set_title("Mean Loss per Epoch")
        ax.grid(True, alpha=0.3, axis="y")

        fig.tight_layout(rect=[0, 0, 1, 0.96])
        fig.savefig(os.path.join(output_dir, "sft_training_dashboard.png"), dpi=150)
        plt.close(fig)
        log.info(f"Training dashboard saved to {output_dir}/sft_training_dashboard.png")

        # === Figure 2: Dataset reward analysis ===
        fig2, axes2 = plt.subplots(1, 3, figsize=(16, 5))
        fig2.suptitle("SFT Training Data — Reward Analysis", fontsize=14, fontweight="bold")
        task_colors = {"easy": "#22c55e", "medium": "#f59e0b", "hard": "#ef4444"}

        # Load original data to get reward info
        reward_by_task = {}
        try:
            with open(SFT_DATA_FILE) as f:
                for line in f:
                    ex = json.loads(line.strip())
                    if ex.get("reward") is not None and ex["reward"] >= MIN_REWARD:
                        task = ex.get("task", "unknown")
                        reward_by_task.setdefault(task, {"rewards": [], "days": []})
                        reward_by_task[task]["rewards"].append(ex["reward"])
                        reward_by_task[task]["days"].append(ex.get("day", 0))
        except Exception:
            pass

        if reward_by_task:
            # Panel 1: Reward by day per task
            ax = axes2[0]
            for task in ["easy", "medium", "hard"]:
                if task in reward_by_task:
                    days = reward_by_task[task]["days"]
                    rewards = reward_by_task[task]["rewards"]
                    # Sort by day
                    paired = sorted(zip(days, rewards))
                    ax.plot([p[0] for p in paired], [p[1] for p in paired],
                            color=task_colors.get(task, "#888"), alpha=0.6, linewidth=1, label=task)
            ax.set_xlabel("Day")
            ax.set_ylabel("Reward")
            ax.set_title("Reward by Day")
            ax.legend()
            ax.grid(True, alpha=0.3)

            # Panel 2: Reward histogram per task
            ax = axes2[1]
            for task in ["easy", "medium", "hard"]:
                if task in reward_by_task:
                    ax.hist(reward_by_task[task]["rewards"], bins=30, alpha=0.5,
                            color=task_colors.get(task, "#888"), label=task, edgecolor="#000")
            ax.set_xlabel("Reward")
            ax.set_ylabel("Count")
            ax.set_title("Reward Distribution")
            ax.legend()
            ax.grid(True, alpha=0.3)

            # Panel 3: Mean reward bar chart
            ax = axes2[2]
            labels, means, colors = [], [], []
            for task in ["easy", "medium", "hard"]:
                if task in reward_by_task:
                    r = reward_by_task[task]["rewards"]
                    labels.append(f"{task}\n(n={len(r)})")
                    means.append(sum(r) / len(r))
                    colors.append(task_colors.get(task, "#888"))
            ax.bar(labels, means, color=colors, width=0.5)
            ax.set_ylabel("Mean Reward")
            ax.set_title("Mean Reward by Task")
            ax.grid(True, alpha=0.3, axis="y")
        else:
            for ax in axes2:
                ax.text(0.5, 0.5, "No reward data", ha="center", va="center",
                        transform=ax.transAxes, color="#888")

        fig2.tight_layout(rect=[0, 0, 1, 0.94])
        fig2.savefig(os.path.join(output_dir, "sft_data_rewards.png"), dpi=150)
        plt.close(fig2)
        log.info(f"Data reward analysis saved to {output_dir}/sft_data_rewards.png")

        # --- Save raw data as JSON ---
        curve_data = {
            "steps": steps, "losses": losses,
            "lr_steps": lr_steps, "lrs": lrs,
            "eval_steps": eval_steps, "eval_losses": eval_losses,
        }
        data_path = os.path.join(output_dir, "sft_training_log.json")
        with open(data_path, "w") as f:
            json.dump(curve_data, f, indent=2)
        log.info(f"Training log saved to {data_path}")

    except ImportError:
        log.warning("matplotlib not installed — skipping curve plots. pip install matplotlib")
    except Exception as e:
        log.error(f"Failed to plot training curves: {e}")


def main():
    train_start = time.time()
    dataset = load_data()

    log.info(f"Dataset size: {len(dataset)}")
    log.info(f"Model: {MODEL_NAME}")
    log.info(f"Epochs: {NUM_EPOCHS}, batch={BATCH_SIZE}, grad_accum={GRAD_ACCUM}")
    log.info(f"Max seq length: {MAX_SEQ_LENGTH}")
    log.info(f"Learning rate: {LEARNING_RATE}")
    log.info(f"Output: {OUTPUT_DIR}")

    # Load model with Unsloth (4-bit quantized)
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=True,
        dtype=None,
    )

    # Apply LoRA via Unsloth
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        lora_alpha=32,
        lora_dropout=0.0,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    # SFT config — TRL auto-applies chat template from the tokenizer
    training_args = SFTConfig(
        output_dir=OUTPUT_DIR,
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM,
        learning_rate=LEARNING_RATE,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        weight_decay=0.01,
        bf16=True,
        logging_steps=5,
        save_strategy="epoch",
        save_total_limit=2,
        max_seq_length=MAX_SEQ_LENGTH,
        seed=42,
        report_to="none",
        # Train only on assistant responses, not system/user prompts
        assistant_only_loss=True,
        dataset_num_proc=2,
    )

    # Formatting function required by Unsloth's patched SFTTrainer
    def formatting_func(examples):
        # The tokenizer can automatically handle both single rows and batches
        texts = tokenizer.apply_chat_template(
            examples["messages"],
            tokenize=False,
            add_generation_prompt=False
        )

        # Unsloth strictly requires a list.
        # If the tokenizer returned a single string, wrap it in a list.
        if isinstance(texts, str):
            return [texts]

        # If it's already a list (because it was batched), just return it.
        return texts

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        args=training_args,
        formatting_func=formatting_func,
    )

    log.info("Starting SFT training...")
    trainer.train()

    train_time = time.time() - train_start
    log.info(f"SFT training finished in {train_time:.1f}s ({train_time/60:.1f}min)")

    # Save LoRA adapter + tokenizer
    log.info(f"Saving LoRA adapters to {OUTPUT_DIR}")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    # Save merged 16-bit model for GRPO continuation (Option A)
    merged_dir = OUTPUT_DIR.rstrip("/") + "_merged"
    log.info(f"Saving merged model to {merged_dir}")
    model.save_pretrained_merged(merged_dir, tokenizer, save_method="merged_16bit")

    # Push merged 16-bit model directly to the Hub
    log.info("Pushing merged model to Hugging Face Hub...")
    model.push_to_hub_merged(
        "saketh1201/Qwen3-4B-Inventory-SFT",  # HuggingFace Hub repo
        tokenizer,
        save_method="merged_16bit",
        token=os.environ.get("HF_TOKEN"),
    )
    log.info("Model pushed to Hugging Face Hub.")

    # Plot training curves
    log.info("Generating training curves...")
    plot_training_curves(trainer, OUTPUT_DIR, dataset)

    # Upload training plots, logs, and dataset to the Hub
    log.info("Uploading training plots, logs, and dataset to the Hub...")
    try:
        from huggingface_hub import HfApi
        api = HfApi()
        # Upload plots and logs from OUTPUT_DIR
        api.upload_folder(
            folder_path=OUTPUT_DIR,
            repo_id="saketh1201/Qwen3-4B-Inventory-SFT",
            repo_type="model",
            allow_patterns=["*.png", "*.json"],
            token=os.environ.get("HF_TOKEN"),
        )
        # Upload the SFT training dataset
        api.upload_file(
            path_or_fileobj=SFT_DATA_FILE,
            path_in_repo=f"data/{SFT_DATA_FILE}",
            repo_id="saketh1201/Qwen3-4B-Inventory-SFT",
            repo_type="model",
            token=os.environ.get("HF_TOKEN"),
        )
        log.info("Successfully uploaded plots, logs, and dataset!")
    except Exception as e:
        log.error(f"Failed to upload artifacts: {e}")

    log.info("SFT training complete.")


if __name__ == "__main__":
    main()